// Fixed interface copy only. Never pass user answers or generated analysis here.
export const interfaceEnglish = {
  "Gemini 服務目前忙碌或暫時不可用，已自動重試並切換備援模型但仍失敗，請稍後再試。": "Gemini is busy or temporarily unavailable. Automatic retries and fallback models were unsuccessful. Please try again later.",
  "AI API 額度或頻率限制已達上限，請稍後再試。": "The AI usage or rate limit has been reached. Please try again later.",
  "AI 分析逾時，請稍後再試或改用較小的檔案。": "AI analysis timed out. Please try again later or use a smaller file.",
  "AI 服務暫時無法完成分析，請稍後再試。": "The AI service cannot complete the analysis right now. Please try again later.",
  "檔案格式不支援，請上傳 .ppt、.pptx 或 .pdf。": "Unsupported file format. Please upload a .ppt, .pptx, or .pdf file.",
  "檔案內容是空的，請重新上傳。": "The file is empty. Please upload it again.",
  "檔案太大，請上傳 25MB 以下的 PPT/PDF。": "The file is too large. Please upload a PPT or PDF file under 25 MB.",
  "AI 回傳格式不是 JSON，請重新生成。": "The AI response was not valid JSON. Please generate the survey again.",
  "AI 回傳格式不正確，無法建立問卷草稿。": "The AI response format is invalid, so a survey draft could not be created.",
  "AI 沒有產生有效題目，請調整生成重點後再試。": "AI did not generate valid questions. Adjust the focus and try again.",
  "無法讀取檔案文字，請改用 .pptx 或可選取文字的 .pdf。": "Cannot read the file text. Please use a .pptx file or a PDF with selectable text.",
  "請先上傳 PPT 或 PDF 檔案。": "Please upload a PPT or PDF file first.",
  "正在建立背景任務...": "Starting survey generation…",
  "任務已建立，等待背景處理。": "Your task is queued and waiting to be processed.",
  "AI 正在分析檔案並產生問卷草稿。": "AI is analyzing your file and generating a survey draft.",
  "AI 正在背景分析檔案並產生問卷草稿。": "AI is analyzing your file in the background and generating a survey draft.",
  "問卷草稿已產生。": "Your survey draft is ready.",
  "AI 問卷產生失敗。": "AI survey generation failed.",
  "問卷產生失敗。": "Survey generation failed.",
  "背景任務處理中，系統會自動查詢結果。": "Your task is running in the background. Results will appear automatically.",
  "個": " items", "與": " and ",
  "請輸入寄送至": "Enter the verification code sent to ",
  "的 6 位數驗證碼": " (6 digits)",
  "為帳號多加一道保護": "Add another layer of account protection",
  "登入時使用信箱驗證碼確認身份": "Verify your identity with an email code when you log in",
  "輸入您的電子郵件，我們會寄送驗證碼確認身分。": "Enter your email and we will send a code to verify your identity.",
  "啟用後，下次登入時需輸入信箱驗證碼才能進入帳號。": "Once enabled, you will need an email verification code each time you log in.",
  "我們已將驗證碼寄送至": "We have sent a verification code to",
  "重新寄送": "Resend", "驗證": "Verify", "連線失敗，請稍後再試": "Connection failed. Please try again later.",
  "請輸入正確的電子郵件格式": "Please enter a valid email address.",
  "驗證碼寄送至信箱": "Verification code sent by email", "可在個人資料停用": "You can disable this in your profile",
  "修改檔案名稱": "Rename file", "移到「": "Move to “", "移到未分類": "Move to unfiled items",
  "目前沒有未分類檔案。": "There are no unfiled items.", "載入中…": "Loading…", "載入失敗：": "Could not load: ",
  "找不到符合「": "No files match “", "」的檔案，請試試其他關鍵字。": "”. Try another search term.",
  "· 刪除時間": "· Deleted", "儲存中": "Saving…", "刪除中": "Deleting…", "刪除": "Delete", "還原中": "Restoring…",
  "從問卷建立、回饋蒐集到 AI 輔助分析，系統協助顧問快速整理文字回饋，產生清楚的分類結果與分析紀錄。": "Create surveys, collect feedback, and use AI to organize written responses into clear categories and analysis records.",
  "立即建立帳號，使用問卷管理與 AI 分析助理，快速整理文字回饋並查看分析結果。": "Create an account to manage surveys, organize written feedback with AI, and view your analysis results.",
  "立即開始使用": "Get started", "人作答": "responses", "人": "respondents", "還有": "There are",
  "筆回答，點此查看全部 →": "more responses. View all →", "平均": "Average", "分": "points", "平均分數": "Average score",
  "份回答": "responses", "題": "questions", "總覽": "Overview", "回覆資料": "Response data", "評分統計": "Rating statistics",
  "題評分題": "rating questions", "文字與選擇題摘要": "Text and choice question summary", "題非評分題": "non-rating questions",
  "查看全部": "View all", "共": "Total:", "可橫向捲動查看所有題目": "Scroll horizontally to view all questions",
  "正在載入問卷詳情…": "Loading survey details…", "正在整理題目、統計與回覆資料，請稍候。": "Preparing questions, statistics, and responses. Please wait.",
  "已開啟雙因子驗證": "Two-factor authentication enabled", "下次登入時會要求輸入驗證碼。": "You will be asked for a verification code the next time you log in.",
  "密碼已修改": "Password updated", "你的登入密碼已成功更新。": "Your login password has been updated successfully.",
  "關閉雙因子驗證": "Disable two-factor authentication", "請輸入目前的登入密碼，確認是你本人操作。": "Enter your current password to verify your identity.",
  "知道了": "Got it", "返回問卷中心": "Back to surveys", "填答身分": "Respondent identity",
  "填答者只能在截止時間前送出問卷。": "Responses can only be submitted before the deadline.", "查看問卷": "View survey",
  "問卷已截止": "Survey closed", "已超過填答期限，無法再送出回覆。": "The deadline has passed. Responses can no longer be submitted.",
  "輸入其他邀請碼": "Enter another invite code", "正在送出你的問卷回覆，請稍候。": "Submitting your responses. Please wait.",
  "題已填": "questions answered", "填答人身分": "Respondent identity", "謝謝你的回覆": "Thank you for your response",
  "你的問卷回覆已送出。": "Your survey responses have been submitted.", "填寫另一份": "Complete another survey",
  "題目方向": "Question focus", "生成重點": "Generation focus", "垃圾桶": "Trash", "垃圾桶是空的": "Trash is empty",
  "刪除的資料夾或檔案會暫時放在這裡。": "Deleted folders and files are temporarily kept here.", "返回收藏": "Back to projects",
  "還原項目會回到收藏；永久刪除後將無法復原。": "Restored items return to your projects. Permanently deleted items cannot be recovered.",
  "刪除時間：": "Deleted: ", "包含": "Contains", "已還原": "Restored", "確定要永久刪除「": "Permanently delete “",
  "」嗎？此操作無法復原。": "”? This cannot be undone.", "分類": "Category", "分析內容": "Analysis", "份有效回答": "valid responses",
  "這批資料沒有產生任何分類結果。": "No classification results were generated for this data.", "分類完成，共": "Classification complete. Total:",
  "個類別。": "categories.", "大類別": "Main category", "子類別": "Subcategory", "問卷回覆內容": "Survey response",
  "判斷原因與說明": "Reasoning and explanation", "受試者建議摘要": "Summary of respondent suggestions",
  "（彙整摘要暫時失敗，以下為個別意見簡易拼接，非完整統整）": "(Summary generation failed. Individual comments are shown below without a combined summary.)",
  "錯誤原因：": "Error: ", "這份問卷沒有開放式文字題可供分類，以上為評分題統計結果。": "This survey has no open-ended questions to classify. Rating statistics are shown above.",
  "（送出後將自動分類）": "(Automatically classified after sending)", "確定要刪除「": "Delete “",
  "」嗎？刪除後可在專案管理的最近刪除中還原。": "”? You can restore it from Recently deleted in Projects.",
  "對話載入中...": "Loading conversation…", "免登入瀏覽 · 僅能檢視此對話，無法傳送指令或修改內容": "No login required · View only. You cannot send commands or edit this conversation.",
  "無法開啟來源對話。": "Cannot open the source conversation.", "請輸入檔案名稱。": "Please enter a file name.",
  "檔案名稱不能包含斜線或特殊符號。": "File names cannot contain slashes or special characters.", "檔案名稱過長，請縮短後再試。": "The file name is too long. Please shorten it.",
  "重新命名失敗，請稍後再試。": "Could not rename the file. Please try again later.", "來源對話": "Source conversation", "點擊下載": "Click to download",
  "載入失敗": "Could not load", "找不到這個檔案的來源對話。": "The source conversation for this file could not be found.",
  "來源對話已刪除或無法存取。": "The source conversation was deleted or is inaccessible.", "無法開啟來源對話，請稍後再試。": "Cannot open the source conversation. Please try again later.",
  "無法確認來源對話，請重新整理後再試。": "Cannot verify the source conversation. Refresh and try again.",
  "伺服器未回傳檔案名稱，請重新整理確認。": "The server did not return a file name. Please refresh to check.",
  "下載失敗，請稍後再試。": "Download failed. Please try again later.", "請先登入後再查看專案管理。": "Please log in to view your projects.",
  "新增分析失敗，請稍後再試": "Could not create an analysis. Please try again later.", "正在刪除...": "Deleting…", "正在移到垃圾桶，請稍候。": "Moving to trash. Please wait.",
  "註冊並登入系統，開始建立問卷或管理分析專案。": "Sign up and log in to create surveys or manage analysis projects.",
  "建立問卷蒐集回饋，或上傳外部問卷與文字資料。": "Create a survey to collect feedback, or upload existing surveys and text data.",
  "透過 AI 分析助理整理文字回饋，產生分類結果與分析紀錄。": "Use the AI assistant to organize written feedback into categories and analysis records.",
  "將分析結果保存至專案中，方便後續查詢、整理與追蹤。": "Save analysis results to projects for future reference and follow-up.",
  "簡答": "Short answer", "短答": "Short answer", "詳答": "Long answer", "單選": "Single choice", "多選": "Multiple choice", "複選": "Multiple choice", "評分": "Rating", "問答": "Open-ended",
  "未填": "Not answered", "未設定": "Not set", "複製失敗，請手動複製邀請碼": "Copy failed. Please copy the invite code manually.",
  "無法複製連結，請手動選取填寫連結。": "Cannot copy the link. Please select and copy the survey link manually.",
  "請選擇截止日期與時間。": "Please select a deadline date and time.", "截止時間已更新。": "Deadline updated.", "截止時間更新失敗。": "Could not update the deadline.",
  "已複製": "Copied", "複製代碼": "Copy code", "匯入中...": "Importing…", "匯入 Chat 分析": "Import for chat analysis",
  "填寫連結": "Survey link", "短連結產生中...": "Generating short link…", "產生中": "Generating…", "複製連結": "Copy link",
  "剛剛": "Just now", "圖片太大": "Image too large", "請選擇小於 2MB 的圖片後再上傳。": "Please upload an image smaller than 2 MB.",
  "頭像": "Profile photo", "頭像上傳失敗": "Profile photo upload failed", "目前無法更新頭像，請稍後再試。": "Cannot update your profile photo. Please try again later.",
  "目前無法儲存資料，請稍後再試。": "Cannot save your changes. Please try again later.", "請重新登入": "Please log in again", "操作失敗": "Action failed",
  "登入狀態已失效，請重新登入後再試。": "Your session has expired. Please log in again.", "目前無法完成操作，請稍後再試。": "Cannot complete this action. Please try again later.",
  "載入個人資料失敗": "Could not load your profile", "找不到問卷代碼": "Survey code not found", "載入問卷資料失敗": "Could not load survey data",
  "載入問卷回覆失敗": "Could not load survey responses", "載入問卷詳情失敗": "Could not load survey details", "截止時間更新失敗": "Could not update the deadline",
  "頭像儲存失敗": "Could not save your profile photo", "請重新登入後再試": "Please log in again and retry", "儲存失敗，請稍後再試": "Save failed. Please try again later.",
  "更新個人資料": "Update profile", "請先輸入密碼。": "Please enter your password.", "已關閉雙因子驗證": "Two-factor authentication disabled",
  "雙因子驗證已成功關閉，之後登入時不會再要求輸入驗證碼。": "Two-factor authentication is now disabled. You will no longer be asked for a verification code when logging in.",
  "密碼輸入錯誤，請重新輸入。": "Incorrect password. Please try again.", "伺服器發生錯誤，請稍後再試。": "A server error occurred. Please try again later.",
  "查看基本資料": "View profile", "查看安全設定": "View security settings", "查看我的問卷": "View my surveys", "已開啟": "Enabled",
  "開啟雙因子驗證": "Enable two-factor authentication", "問卷時間排序": "Sort surveys by date", "關閉通知": "Dismiss notification",
  "隱藏密碼": "Hide password", "顯示密碼": "Show password", "隱藏": "Hide", "顯示": "Show", "確認中...": "Confirming…", "確認關閉": "Confirm disabling",
  "請先登入後再建立問卷。": "Please log in to create a survey.", "請輸入問卷標題。": "Please enter a survey title.",
  "問卷截止時間必須晚於現在。": "The survey deadline must be in the future.", "每個題目都需要填寫題目文字。": "Please enter text for every question.",
  "填答身分設定": "Respondent identity settings", "問卷已建立": "Survey created", "把邀請碼分享給填答者，就可以開始收集回覆。": "Share the invite code to start collecting responses.",
  "複製邀請碼": "Copy invite code", "複製填寫連結": "Copy survey link", "請輸入邀請碼。": "Please enter an invite code.",
  "找不到這組邀請碼，請確認後再試一次。": "Invite code not found. Please check it and try again.", "伺服器連線失敗，請稍後再試。": "Cannot connect to the server. Please try again later.",
  "請填寫身分後再送出問卷。": "Please enter your identity before submitting.", "請輸入回答": "Enter your answer", "讀取中": "Loading…",
  "請輸入姓名、學號、員工編號或可辨識身分": "Enter your name, student ID, employee ID, or another identifier",
  "目前沒有已刪除的項目": "No deleted items", "請先登入後再匯出檔案。": "Please log in to export files.",
  "無法生成檔案，請稍後再試。": "Cannot generate the file. Please try again later.", "未收到完成確認，請到匯出檔案確認後再試。": "Completion has not been confirmed. Check Exported files before retrying.",
  "請檢查網路連線後再試。": "Check your internet connection and try again.", "請先開啟一個工作區": "Please open a workspace first",
  "這個工作區還沒同步完成，請先傳送一則訊息後再邀請檢視": "This workspace has not finished syncing. Send a message before inviting viewers.",
  "產生邀請連結失敗": "Could not create an invite link", "產生邀請連結失敗，請稍後再試": "Could not create an invite link. Please try again later.",
  "載入問卷清單失敗": "Could not load the survey list", "網路錯誤": "Network error", "AI 沒有回傳內容，請稍後再試。": "AI returned no content. Please try again later.",
  "已刪除工作區，並移至最近刪除": "Workspace moved to Recently deleted", "刪除失敗，請稍後再試": "Delete failed. Please try again later.",
  "選擇問卷分析": "Select a survey to analyze", "邀請連結無效或已失效": "The invite link is invalid or expired",
  "無法載入對話，請稍後重新整理。": "Cannot load the conversation. Please refresh later.", "搜尋歷史對話紀錄（唯讀）": "Search conversation history (read only)",
  "分享對話": "Shared conversation", "分享的對話紀錄": "Shared conversation history", "上傳檔案（唯讀模式無法使用）": "Upload files (unavailable in read-only mode)",
  "此對話僅供檢視，無法輸入指令...": "This conversation is view only. Commands are disabled…", "對話輸入（唯讀）": "Conversation input (read only)",
  "傳送訊息（唯讀模式無法使用）": "Send message (unavailable in read-only mode)", "連結已複製，可以分享給其他人了。": "Link copied. You can now share it with others.",
  "無法自動複製，請選取上方連結手動複製。": "Could not copy automatically. Select the link above and copy it manually.", "關閉邀請視窗": "Close invitation dialog",
  "進入工作區": "Open workspace", "查看專案管理": "View projects", "查看最近刪除": "View recently deleted", "查看個人資料": "View profile",
  "建立問卷頁面": "Create survey page", "PPT 問卷生成頁面": "Presentation survey generator", "填寫問卷頁面": "Survey response page",
};
